block/quiver

- lib/src/main/kotlin/app/cash/quiver/extensions/List.kt
- lib/src/test/kotlin/app/cash/quiver/extensions/OptionTest.kt
Hey all 👋
Very exciting to see this initiative 🙌 Glad to see you're using, and hopefully enjoying Arrow.
This PR fixes an issue of nested generic null, which is typically why you'd want to use `Option`. If `A` is not constrained to `Any`, `A : Any`, then a _nested null_ can occur. Relying on `mapNotNull + orNull` filters out the  _nested null_. I updated the test to reflect the issue.
(I could not build the project locally due to missing `./gradlew` and some CashApp specific build settings) but I didn't really investigate it much.
I saw you were re-adding some APIs that we've deprecated, and introduced some new methods. I think these `Option` based methods could also be merged upstream into Arrow. Although I am also excited that there is a library introducing new types like `Outcome`, and …
> Fix nested null bug

- gradle/libs.versions.toml
- lib/build.gradle.kts
- lib/custom-styles.css
- lib/module.md
Shows the dark logo in dark mode, and the light logo in light mode!
Bonus: allows us to set a dark/light mode version of images in other documentation (e.g. diagrams).
This pull request is dedicated to @millyrowboat ✨ 
https://user-images.githubusercontent.com/1646536/227755127-aa16764b-220c-4a05-9a79-f28e48b90589.mov
> Makes logo image theme-aware

- lib/api/lib.api
- lib/src/main/kotlin/app/cash/quiver/Outcome.kt
- lib/src/main/kotlin/app/cash/quiver/extensions/Either.kt
- lib/src/main/kotlin/app/cash/quiver/extensions/Option.kt
This PR is introduces **binary breaking change** by replacing `suspend` in some cases with `inline`. It is however source compatible. I am not sure how strict binary breaking changes are being dealt with atm.
It also exposes that `tapLeft` is duplicated with the Arrow API, hence `EXTENSION_SHADOWED_BY_MEMBER`
> Use inline where possible

- lib/src/main/kotlin/app/cash/quiver/extensions/Map.kt
- lib/src/test/kotlin/app/cash/quiver/extensions/MapTest.kt
This PR fixes a bug with _nested null_, or when `V` is `null`, in `Map.getOption`.
> Fix Map.getOption nested null bug

- lib/api/lib.api
- lib/src/main/kotlin/app/cash/quiver/extensions/Either.kt
- lib/src/main/kotlin/app/cash/quiver/extensions/Ior.kt
- lib/src/main/kotlin/app/cash/quiver/extensions/Nullable.kt
- lib/src/test/kotlin/app/cash/quiver/extensions/EitherTest.kt
- lib/src/test/kotlin/app/cash/quiver/extensions/IorTest.kt
- lib/src/test/kotlin/app/cash/quiver/extensions/NullableTest.kt
- testing-lib/api/testing-lib.api
- testing-lib/src/main/kotlin/app/cash/quiver/arb/Arbitrary.kt
This PR adds `zip` for `Nullable`, `Either` & `Ior`. It has currently omitted the `zip` method for `Option`, because it suffers from the same `@Suppress("EXTENSION_SHADOWED_BY_MEMBER")` issue as described in https://github.com/cashapp/quiver/pull/32.
We can of course also add it ahead of time, and we can also provide OpenRewrite recipes for automatically migrating from Arrow to Quiver.
> Either, Nullable & Ior zip

- lib/src/main/kotlin/app/cash/quiver/Outcome.kt
- lib/src/test/kotlin/app/cash/quiver/OutcomeTest.kt
The current implementations of `traverse`/`sequence` does not respect the expected laws. Let's compare with Haskell (where `Just` is the equivalent of `Some`, and `[x]` means `listOf(x)`).
```haskell
> mapM (\x -> Just 3) (Left 2)
Just (Left 2)
> mapM (\x -> [3]) (Left 2)
[Left 2]
```
However, our current implementation would return `None` and an empty list in those cases. This PR implements the law-abiding implementations, which return `Failure` wrapped in the corresponding type instead of the "error path" of those.
> Fix Outcome.traverse/sequence

- lib/api/lib.api
- lib/src/main/kotlin/app/cash/quiver/extensions/Either.kt
- lib/src/test/kotlin/app/cash/quiver/extensions/EitherTest.kt
We've decided in Arrow to continue deprecating and removing `traverse`, therefore I am PR'ing `traverse` to Quiver.
However when doing so I realised that it's not possible to conveniently replace the `traverse` method in Arrow, this is shown by `@Suppress("EXTENSION_SHADOWED_BY_MEMBER")`.
So as long as `traverse` is not actually removed in Arrow, the Kotlin compiler will always prefer the _instance method_ rather than the _extension function_. Regardless if `app.cash.quiver.extensions` is imported. This is clear from the named imports required in the tests `import app.cash.quiver.extensions.traverse as quiverTraverse`.
We can continue merging this as-is, such that it's ready for when Arrow 2.0 is released. It would be extremely easy to provide an `OpenRewrite` recipe to automatically …
> Add Either.traverse

- lib/src/test/kotlin/app/cash/quiver/OutcomeTest.kt
- testing-lib/src/main/kotlin/app/cash/quiver/matchers/Matchers.kt
Prior to this patch, calling `shouldBePresent` on an `Absent` value resulted in `java.lang.AssertionError: () -> kotlin.String`.
This commit fixes the message passed in, which now results in the following error: `java.lang.AssertionError: Expecting Present, got absent`. This is the expected functionality.
> Fixes assertion error thrown when Outcome is Absent

- CHANGELOG.md
- gradle/libs.versions.toml
- lib/api/lib.api
- lib/src/main/kotlin/app/cash/quiver/extensions/Result.kt
- lib/src/test/kotlin/app/cash/quiver/extensions/ResultTest.kt
Result is a kotlin native type that is similar to ErrorOr<T>
This PR introduces Result.toEither() as a shortcut for transforming Results into Arrowland.
> Adds Result.toEither()

- lib/build.gradle.kts
- lib/dokka/templates/includes/header.ftl
Adds a link to https://github.com/cashapp/quiver in the navigation bar, next to the search input.
This makes it possible to navigate to GitHub from any page.
| Before | After |
| ------------- | ------------- |
|<img width="640" alt="image" src="https://github.com/cashapp/quiver/assets/1646536/8df790da-aa0b-49bb-8954-a5e42a3d4834">|<img width="639" alt="image" src="https://github.com/cashapp/quiver/assets/1646536/52447e3f-3af4-4265-8a94-d5da9737b6ab">|
Based on [Dokka documentation](https://kotlin.github.io/dokka/1.8.0-SNAPSHOT/user_guide/output-formats/html/#custom-html-pages).
> Adds GitHub link to navigation header

- lib/api/lib.api
- lib/src/main/kotlin/app/cash/quiver/extensions/Option.kt
- lib/src/test/kotlin/app/cash/quiver/extensions/OptionTest.kt
Clawed back from #53 
- orEmpty is a convenience function that we've been using in our codebases, that will return an empty string if your Option is None
- Wondering now if that should only be allowed to be called on a Option<String> context. Thoughts? As in:
```
fun Option<String>.orEmpty(f: (String) -> String): String = this.map(f).getOrElse { "" }
```
> Add 'orEmpty' convenience function to Option

- lib/api/lib.api
- lib/src/main/kotlin/app/cash/quiver/extensions/Option.kt
- lib/src/test/kotlin/app/cash/quiver/extensions/OptionTest.kt
This change brings `Option` in line with `Either`'s version see: https://github.com/cashapp/quiver/blob/9862a2af9c6000e12d07bf8fb8d158a21ebd9aa7/lib/src/main/kotlin/app/cash/quiver/extensions/Either.kt#L34
It would be expected behaviour to not have all the alternatives for the `or` to execute until it is actually needed, especially if there is an expensive side-effect involved.
> Make Option's  function lazy, deprecate the eager version

- lib/api/lib.api
- lib/src/main/kotlin/app/cash/quiver/extensions/Either.kt
- lib/src/main/kotlin/app/cash/quiver/extensions/Iterable.kt
- lib/src/main/kotlin/app/cash/quiver/extensions/List.kt
- lib/src/main/kotlin/app/cash/quiver/extensions/Option.kt
- lib/src/test/kotlin/app/cash/quiver/extensions/EitherTest.kt
- lib/src/test/kotlin/app/cash/quiver/extensions/OptionTest.kt
- lib/src/test/kotlin/app/cash/quiver/extensions/TraverseTest.kt
This back-ports some of the `traverse` methods deprecated in Arrow.
- Either.traverseOption synonym
- Iterable.traverse(f -> Either) and Iterable.traverseEither synonym
- Iterable.traverse(f -> Option) and Iterable.traverseOption synonym
- Option.traverse(f -> Either) and Option.traverseEither synonym
- Option.traverse(f -> Iterable)
> backport Arrow deprecated traverse functions

- CHANGELOG.md
- lib/api/lib.api
- lib/src/main/kotlin/app/cash/quiver/extensions/Result.kt
- lib/src/test/kotlin/app/cash/quiver/extensions/ResultTest.kt
This will enable the same behaviour as `Either.catch`, i.e., catching only non-fatal exceptions.
> Add Result.catch function to catch non-fatal exceptions

- lib/api/lib.api
- lib/src/main/kotlin/app/cash/quiver/Outcome.kt
- lib/src/main/kotlin/app/cash/quiver/extensions/Result.kt
- lib/src/test/kotlin/app/cash/quiver/OutcomeTest.kt
- lib/src/test/kotlin/app/cash/quiver/extensions/ResultTest.kt
- testing-lib/api/testing-lib.api
- testing-lib/src/main/kotlin/app/cash/quiver/arb/Arbitrary.kt
`OutcomeOf<A>` is essentially a `Result<Option<A>>` as the error side is locked down to a `Throwable`.  This PR makes it easier to convert between the two.
> Adds in conversion to and from Result<Option<A>> and OutcomeOf<A>

- lib/api/lib.api
- lib/src/main/kotlin/app/cash/quiver/raise/OutcomeBuilder.kt
- lib/src/test/kotlin/app/cash/quiver/OutcomeOfRaiseTest.kt
This PR adds a specialised Raise DSL for `OutcomeOf<A>`.
`Result<Option<A>>`, `ErrorOr<Option<A>>` and `OutcomeOf<A>` are isomorphic, meaning they can be converted between each other without loss of information.  Given that is the case we can increase the interoperability between them inside the `outcomeOf` DSL block.
For example:
```kotlin
val outcomeValue : OutcomeOf<Int> = outcomeOf {
val a = Present(1).bind()
val b: Int = Result.success(1.some()).bind()
val c: Int = Either.Right(2).bind()
val d: Int = Either.Right(4.some()).bindOption()
val nullValue: Int? = 1
val e: Int = ensureNotNull(nullValue)
val f: Int = nullValue.bindNull()
val g: Int = Result.success(1).bindResult()
val result = a + b + c + d + e + f + g
ensure(result > 9)
result
}
outcomeValue.shouldBePresent().shouldBe(11) …
```
> Adds specialised outcomeOf Raise DSL to allow for greater interoperability with Results and Eithers

- lib/api/lib.api
- lib/src/main/kotlin/app/cash/quiver/Outcome.kt
- lib/src/test/kotlin/app/cash/quiver/OutcomeTest.kt
This adds a new method similar to `asEither`.
> Adds OutcomeOf::asResult with an onAbsent conversion

- lib/api/lib.api
- lib/src/main/kotlin/app/cash/quiver/continuations/OutcomeEagerEffectScope.kt
This makes this type inline with the other Arrow types as everything should use the Raise DSL
> Deprecates Outcome DSL syntax preferring the Raise DSL

- CHANGELOG.md
- gradle.properties
By removing `Validated` and associated methods, we are introducing a breaking change, and should use an appropriate [semantic version](https://semver.org/) indicating this.
* Upgrades Arrow to 2.x (Hugo Müller-Downing)
* Removes `OutcomeEffectScope` and `OutcomeEagerEffectScope` in favour of `OutcomeBuilder` (Hugo Müller-Downing)
* Removes methods interacting with `Validated`, as `Validated` is now deprecated (Hugo Müller-Downing)
* Replaces `ValidatedNel` with a typealias of `Either<NonEmptyList<E>, A>` (Hugo Müller-Downing)
> Release 1.0.0

- .github/workflows/Documentation.yml
Fixes failures to push documentation relating to the [deprecation of actions/upload-artifact@v3](https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/).
> Upgrades upload-pages-artifact from v2 to v3

- lib/api/lib.api
- lib/src/main/kotlin/app/cash/quiver/extensions/Validated.kt
- lib/src/test/kotlin/app/cash/quiver/extensions/ValidatedTest.kt
- testing-lib/api/testing-lib.api
- testing-lib/src/main/kotlin/app/cash/quiver/matchers/Matchers.kt
Backports validNel and invalidNel extension functions which were originally available in Validated, but recently removed in Arrow 2.x.
Adds `shouldBeValid` and `shouldBeInvalid` matchers.
> Adds validNel and invalidNel extension functions

- .github/workflows/Release.yml
Documentation is published via a separate GitHub Action, no need to do it here as well.
> Removes documentation jobs from release action

- lib/src/main/kotlin/app/cash/quiver/extensions/Demand.kt
- lib/src/test/kotlin/app/cash/quiver/extensions/DemandTest.kt
I forgot the package when defining this originally in https://github.com/block/quiver/pull/126.
These extensions should be appropriately namespaced, so the import isn't global (`import demand`).
> Moves demand to the app.cash.quiver.extension package
